// Auto-generated from ML Trading product sheet (70 products, 14 categories).
// Prices intentionally omitted — the sheet had none; owner sets them in the UI.
export const CATALOG = [
  { code: "RTP40", name: "Retatrutide 40mg Pen", category: "Pens", status: "available", qboItemName: "RTP40" },
  { code: "TRP40", name: "Tirzepatide 40mg Pen", category: "Pens", status: "available", qboItemName: "TRP40" },
  { code: "GLP60", name: "Glow60 Pen", category: "Pens", status: "available", qboItemName: "GLP60" },
  { code: "MTP10P", name: "MOTS-C Pen", category: "Pens", status: "inactive", qboItemName: "MTP10P" },
  { code: "RT05", name: "Retatrutide 5mg", category: "Retatrutide", status: "available", qboItemName: "RT05" },
  { code: "RT10", name: "Retatrutide 10mg", category: "Retatrutide", status: "available", qboItemName: "RT10" },
  { code: "RT30", name: "Retatrutide 30mg", category: "Retatrutide", status: "available", qboItemName: "RT30" },
  { code: "RT40", name: "Retatrutide 40mg", category: "Retatrutide", status: "available", qboItemName: "RT40" },
  { code: "TZ05", name: "Tirzepatide 5mg", category: "Tirzepatide", status: "available", qboItemName: "TZ05" },
  { code: "TZ10", name: "Tirzepatide 10mg", category: "Tirzepatide", status: "available", qboItemName: "TZ10" },
  { code: "TZ15", name: "Tirzepatide 15mg", category: "Tirzepatide", status: "available", qboItemName: "TZ15" },
  { code: "TZ20", name: "Tirzepatide 20mg", category: "Tirzepatide", status: "available", qboItemName: "TZ20" },
  { code: "TZ40", name: "Tirzepatide 40mg", category: "Tirzepatide", status: "available", qboItemName: "TZ40" },
  { code: "BP05", name: "BPC-157 5mg", category: "Healing & Recovery", status: "available", qboItemName: "BP05" },
  { code: "BP10", name: "BPC-157 10mg", category: "Healing & Recovery", status: "available", qboItemName: "BP10" },
  { code: "TB05", name: "TB-500 5mg", category: "Healing & Recovery", status: "available", qboItemName: "TB05" },
  { code: "TB10", name: "TB-500 10mg", category: "Healing & Recovery", status: "available", qboItemName: "TB10" },
  { code: "BT05", name: "BPC/TB Blend 5mg/5mg", category: "Healing & Recovery", status: "available", qboItemName: "BT05" },
  { code: "BT10", name: "BPC/TB Blend 10mg/10mg", category: "Healing & Recovery", status: "available", qboItemName: "BT10" },
  { code: "WV10", name: "Wolverine Vial", category: "Healing & Recovery", status: "available", qboItemName: "WV10" },
  { code: "KPV10", name: "KPV 10mg", category: "Healing & Recovery", status: "available", qboItemName: "KPV10" },
  { code: "GH50", name: "GHK-CU 50mg", category: "GHK-CU", status: "available", qboItemName: "GH50" },
  { code: "GH100", name: "GHK-CU 100mg", category: "GHK-CU", status: "available", qboItemName: "GH100" },
  { code: "MC10", name: "MOTS-C 10mg", category: "MOTS-C", status: "available", qboItemName: "MC10" },
  { code: "ND500", name: "NAD+ 500mg", category: "NAD+", status: "available", qboItemName: "ND500" },
  { code: "ND1000", name: "NAD+ 1000mg", category: "NAD+", status: "available", qboItemName: "ND1000" },
  { code: "TS05", name: "Tesamorelin 5mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "TS05" },
  { code: "TS06", name: "Tesamorelin 6mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "TS06" },
  { code: "TS10", name: "Tesamorelin 10mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "TS10" },
  { code: "CJ02", name: "CJC-1295 no DAC 2mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "CJ02" },
  { code: "CD02", name: "CJC-1295 DAC 2mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "CD02" },
  { code: "IP02", name: "Ipamorelin 2mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "IP02" },
  { code: "IP05", name: "Ipamorelin 5mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "IP05" },
  { code: "IG01", name: "IGF-1 LR3 1mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "IG01" },
  { code: "HG10", name: "HGH 10IU", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "HG10" },
  { code: "HF05", name: "HGH Fragment 5mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "HF05" },
  { code: "GP02", name: "GHRP-2 10mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "GP02" },
  { code: "GP06", name: "GHRP-6 10mg", category: "Growth Hormones & Secretagogues", status: "available", qboItemName: "GP06" },
  { code: "SX10", name: "Semax 10mg", category: "Cognitive / Mood", status: "available", qboItemName: "SX10" },
  { code: "SL10", name: "Selank 10mg", category: "Cognitive / Mood", status: "available", qboItemName: "SL10" },
  { code: "DS10", name: "DSIP 10mg", category: "Cognitive / Mood", status: "available", qboItemName: "DS10" },
  { code: "OX10", name: "Oxytocin 10mg", category: "Cognitive / Mood", status: "available", qboItemName: "OX10" },
  { code: "OX02", name: "Oxytocin 2mg", category: "Cognitive / Mood", status: "available", qboItemName: "OX02" },
  { code: "KP10", name: "Kisspeptin 10mg", category: "Cognitive / Mood", status: "available", qboItemName: "KP10" },
  { code: "EP10", name: "Epitalon 10mg", category: "Longevity / Metabolic", status: "available", qboItemName: "EP10" },
  { code: "SS10", name: "SS-31 10mg", category: "Longevity / Metabolic", status: "available", qboItemName: "SS10" },
  { code: "AO05", name: "AOD-9604 5mg", category: "Longevity / Metabolic", status: "available", qboItemName: "AO05" },
  { code: "CG10", name: "Cagrilintide 10mg", category: "Longevity / Metabolic", status: "available", qboItemName: "CG10" },
  { code: "FX10", name: "FOX04-DRI 10mg", category: "Longevity / Metabolic", status: "available", qboItemName: "FX10" },
  { code: "MB100", name: "Methylene Blue 100ml", category: "Longevity / Metabolic", status: "available", qboItemName: "MB100" },
  { code: "TH10", name: "Thymulin 10mg", category: "Longevity / Metabolic", status: "available", qboItemName: "TH10" },
  { code: "MT10", name: "MT-2 10mg", category: "Tanning & Libido", status: "available", qboItemName: "MT10" },
  { code: "MT20", name: "MT-2 10mg", category: "Tanning & Libido", status: "available", qboItemName: "MT20" },
  { code: "MT11", name: "MT-1 10mg", category: "Tanning & Libido", status: "available", qboItemName: "MT11" },
  { code: "PT10", name: "PT-141 10mg", category: "Tanning & Libido", status: "available", qboItemName: "PT10" },
  { code: "SXN", name: "Semax Nasal", category: "Nasals", status: "available", qboItemName: "SXN" },
  { code: "SLN", name: "Selank Nasal", category: "Nasals", status: "available", qboItemName: "SLN" },
  { code: "DSN", name: "DSIP Nasal", category: "Nasals", status: "available", qboItemName: "DSN" },
  { code: "OXN", name: "Oxytocin Nasal", category: "Nasals", status: "available", qboItemName: "OXN" },
  { code: "KPN", name: "Kisspeptin Nasal", category: "Nasals", status: "available", qboItemName: "KPN" },
  { code: "NDN", name: "NAD+ Nasal", category: "Nasals", status: "available", qboItemName: "NDN" },
  { code: "GLN", name: "Glow Nasal", category: "Nasals", status: "available", qboItemName: "GLN" },
  { code: "MTN", name: "Tanning Nasal", category: "Nasals", status: "available", qboItemName: "MTN" },
  { code: "BTN", name: "BPC/TB Nasal", category: "Nasals", status: "available", qboItemName: "BTN" },
  { code: "SLU250", name: "SLU-PP-332 250mcg", category: "Tablets / Capsules", status: "available", qboItemName: "SLU250" },
  { code: "SLU500", name: "SLU-PP-332 500mcg", category: "Tablets / Capsules", status: "available", qboItemName: "SLU500" },
  { code: "TKA", name: "Tongkat Ali", category: "Tablets / Capsules", status: "available", qboItemName: "TKA" },
  { code: "AGP", name: "Alpha GPC", category: "Tablets / Capsules", status: "available", qboItemName: "AGP" },
  { code: "ASH", name: "Ashwagandha", category: "Tablets / Capsules", status: "available", qboItemName: "ASH" },
  { code: "BAC", name: "Bac Water 10ml", category: "Water 10ml", status: "available", qboItemName: null },
] as const;
